### ISSUE TITLE
想请教一下新版本的frp域前置代码修改

### ISSUE THREAD

**Issue by 0xorOne** [DongHuangT1/Frp#1]

**Comment by 0xorOne** [comment]
请问一下对新版本的域前置功能需要修改哪些地方

**Comment by 0xorOne** [comment]
师傅能留个联系方式吗

**Comment by DongHuangT1** [comment]
![code](https://github.com/DongHuangT1/Frp/assets/51707652/1e5db7b1-8f5e-461d-a411-31055ca8da3e)
